C300/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using C300.Models;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace C300.Controllers
{
    public class MainController : Controller
    {
        private IWebHostEnvironment _env;

        #region trends
        [HttpGet]
        public IActionResult trends(int id)
        {
            string productSql = @"SELECT * FROM Product
                                 WHERE Product_ID = {0}";
            List<Product> lstProduct = DBUtl.GetList<Product>(productSql, id);

            // If the record is found, pass the model to the View
            if (lstProduct.Count == 1)
            {
                ViewData["Category"] = GetListProduct();
                return View(lstProduct[0]);
            }
            else
            // Otherwise redirect to the movie list page
            {
                TempData["Message"] = "Product not found.";
                TempData["MsgType"] = "warning";
                return RedirectToAction("ListProduct");
            }
        }
        [HttpPost]
        public IActionResult trendsPost()
        {

            IFormCollection form = HttpContext.Request.Form;
            string trends = form["Trends"].ToString();
            if (ValidUtl.CheckIfEmpty(trends))
            {
                ViewData["Message"] = "Please enter all fields";
                ViewData["MsgType"] = "warning";
                return View("trends");
            }

            return RedirectToAction("Chart");
        }
        #endregion
        #region Chart
        public IActionResult Bar()
        {
            ViewData["Chart"] = "bar";
            ViewData["ShowLegend"] = "false";
            return View("Chart");
        }

        public IActionResult Pie()
        {
            ViewData["Chart"] = "pie";
            ViewData["ShowLegend"] = "true";
            return View("Chart");
        }

        public IActionResult Line()
        {
            ViewData["Chart"] = "line";
            ViewData["ShowLegend"] = "false";
            return View("Chart");
        }

        public IActionResult Chart(int id)
        { 
            string sql = @"SELECT Product_Name AS Product, Quantity 
                         FROM Product
                         WHERE Product_ID = {0}";
            List<Product> list = DBUtl.GetList<Product>(sql, id);

            if (list != null)
            {
                Product pdt = list[0];
                int[] data = new int[]{ pdt.ReorderQty };
                ViewData["Data"] = data;
            }
            else
            {
                TempData["Message"] = "Record does not exist";
                TempData["MsgType"] = "warning";
                return RedirectToAction("trends");
            }

            string[] colors = new[] { "cyan", "lightgreen", "yellow", "lightgrey", "pink", "grey", "blue", "green" };
            string[] grades = new[] { "Anger", "Contempt", "Disgust", "Fear", "Happiness", "Neutral", "Sadness", "Surprise" };
            ViewData["Chart"] = "pie";
            ViewData["Title"] = "Monthly Sales Summary";
            ViewData["ShowLegend"] = "true";
            ViewData["Legend"] = "Cadets";
            ViewData["Colors"] = colors;
            ViewData["Labels"] = grades;

            return View("Chart");
        }
        #endregion
        public MainController(IWebHostEnvironment environment)
        {
            _env = environment;
        }
        private SelectList GetListProduct()
        {
            // Get a list of all genres from the database
            var catSql = DBUtl.GetList("SELECT Category FROM Movie");
            SelectList lstProduct = new SelectList(catSql, "Category");
            return lstProduct;
        }
    }
}

C300/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using C300.Models;
using System.Security.Claims;

namespace C300.Controllers
{
    public class ProductController : Controller
    {
        [AllowAnonymous]
        public IActionResult About()
        {
            return View();
        }
        [Authorize]
        public IActionResult ListProduct()
        {
            List<Product> product = DBUtl.GetList<Product>(
                  @"SELECT Product.Id, Description, Weight, Width, Height, Depth, Type, CategoryDescription, Isle, Shelf, ReorderQty
                    FROM Product, Package, Category, Location 
                    WHERE Product.PackageId = Package.Id
                    AND Product.CategoryId = Category.Id
                    AND Product.LocationId = Location.Id");
            return View(product);

        }
        [Authorize]
        public IActionResult AddProduct()
        {
            ViewData["Category"] = GetListCat();
            ViewData["Package"] = GetListType();
            return View();
        }
        [Authorize]
        [HttpPost]
        public IActionResult AddProduct(Product newProduct)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Category"] = GetListCat();
                ViewData["Package"] = GetListType();
                ViewData["Message"] = "Invalid Input";
                ViewData["MsgType"] = "warning";
                return View("AddProduct");
            }
            else
            {
                string insert =
                   @"INSERT INTO Product(Description, Weight, Width, Height, Depth, PackageId, CategoryId, LocationId, ReorderQty) 
                 VALUES('{0}', {1}, {2}, {3}, {4}, {5}, {6}, {7}, {8})";
                int result = DBUtl.ExecSQL(insert, newProduct.Description, newProduct.Weight, newProduct.Width,
                                           newProduct.Height, newProduct.Depth, newProduct.PackageId,
                                           newProduct.CategoryId,newProduct.LocationId,newProduct.ReorderQty);  

                if (result == 1)
                {
                    TempData["Message"] = "Product Created";
                    TempData["MsgType"] = "success";
                }
                else
                {
                    TempData["Message"] = DBUtl.DB_Message;
                    TempData["MsgType"] = "danger";
                }
                return RedirectToAction("ListProduct");
            }
        }
        [Authorize]
        [HttpGet]
        public IActionResult EditProduct(string name)
        {
            string productSql = @"SELECT * FROM Product
                    WHERE Description = '{0}'";
            List<Product> lstProduct = DBUtl.GetList<Product>(productSql, name);

            if (lstProduct.Count == 1)
            {
                ViewData["Category"] = GetListCat();
                ViewData["ProductType"] = GetListType();
                return View(lstProduct[0]);
            }
            else
            {
                TempData["Message"] = "Product not found.";
                TempData["MsgType"] = "warning";
                return RedirectToAction("ListProduct");
            }
        }
        [Authorize]
        [HttpPost]
        public IActionResult EditProduct(Product product)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Message"] = "Invalid Input";
                ViewData["MsgType"] = "danger";
                return View("EditProduct", product);
            }
            else
            {
                string update = @"UPDATE Product 
                              SET Product.Weight={1}, Product.Width={2}, Product.Height={3}, Product.Depth={4}, Package.Type={5},
                                  Category.CategoryDescription = '{6}', Location.Isle = '{7}', Location.Shelf = '{8}', ReorderQty = {9}              
                              WHERE Product.Id={0} 
                              AND Category.Id = Product.CategoryId, 
                                  Package.Id = Product.PackageId,
                                  Location.Id = Product.LocationId";
                if (DBUtl.ExecSQL(update, product.Id,product.Weight,product.Width, product.Height,
                    product.Depth,product.Type,product.CategoryDescription,
                    product.Isle,product.Shelf,product.ReorderQty)==1)

                {
                    TempData["Message"] = "Product Updated";
                    TempData["MsgType"] = "success";
                }
                else
                {
                    TempData["Message"] = DBUtl.DB_Message;
                    TempData["MsgType"] = "danger";
                }
                return RedirectToAction("ListProduct");
            }            
        }
        [Authorize]
        public IActionResult DeleteProduct(int id)
        {
            string select = @"SELECT * FROM Product 
                              WHERE Id={0}";
            DataTable ds = DBUtl.GetTable(select, id);
            if (ds.Rows.Count != 1)
            {
                TempData["Message"] = "Product record no longer exists.";
                TempData["MsgType"] = "warning";
            }
            else
            {
                string delete = "DELETE FROM Product WHERE Id={0}";
                int res = DBUtl.ExecSQL(delete, id);
                if (res == 1)
                {
                    TempData["Message"] = "Product Deleted";
                    TempData["MsgType"] = "success";
                }
                else
                {
                    TempData["Message"] = DBUtl.DB_Message;
                    TempData["MsgType"] = "danger";
                }
            }
            return RedirectToAction("ListProduct");
        }

        private SelectList GetListCat()
        {
            // Get a list of all genres from the database
            var catSql = DBUtl.GetList("SELECT Id, CategoryDescription FROM Category");
            SelectList lstCat = new SelectList(catSql, "Id", "CategoryDescription");
            return lstCat;
        }

        private SelectList GetListType()
        {
            
            var typeSql = DBUtl.GetList("SELECT Id, Type FROM Package");
            SelectList lstType = new SelectList(typeSql, "Id", "Type");
            return lstType;
        }
    }
}

C300/Views/Main/Chart.cshtml
@section MoreScripts {
    <script language="javascript">

      $(document).ready(function () {
         new Chart(document.getElementById("chart"), {
             type: '@ViewData["Chart"]',
            data: {
               labels: @Json.Serialize(ViewData["Labels"]),
               datasets: [{
                  label: '@ViewData["Legend"]',
                  data: @Json.Serialize(ViewData["Data"]),
                  backgroundColor: @Json.Serialize(ViewData["Colors"]),
                  fill: false
               }]
            },
            options: {
               responsive: false,
               legend: {
                  display: @ViewData["ShowLegend"]
               },
               title: {
                  display: true,
                  text: '@ViewData["Title"]'
                },
                plugins: {
                    labels: {
                        render: 'value'
                    }
                }
            }
         });
      });

    </script>

}
<style>
    .body {
        background-image: linear-gradient(150deg,#FFFFFF,#DDF3FB);
        height: 100vh;
        width: 100%;
    }

</style>
<body class="body">
    <div class="container">
        <canvas id="chart" width="600" height="400"></canvas>
    </div>
</body>

C300/Views/Main/profile.cshtml
<style>
    .body {
        background-image: linear-gradient(150deg,#FFFFFF,#DDF3FB);
        height: 100vh;
        width: 100%;
    }

    h1 {
        font-family: Segoe Print;
        text-align: center;
    }

    .form-group {
        font-family: Ink Free;
        color: #0E0E55;
        text-align: center;
    }

    .offset-md-3 {
        font-family: Lucida Bright;
        text-align: center;
    }
</style>
<body class="body">
    @model UserDetails

    <h1>Welcome</h1>

    <div class="form-group row">
        <div class="form-group row">
            <div class="offset-md-3 col-md-6">
                <a asp-controller="Main"
                   asp-action="update">
                    Update Details
                </a>
                <p></p>
                <a asp-controller="Main"
                   asp-action="trends">
                    View Trends
                </a>
                <p></p>
                <a asp-controller="Product"
                   asp-action="ListProduct">
                    View Product
                </a>
            </div>

        </div>

        <div class="offset-md-3 col-md-6">
            <p>
                “Don’t try to force anything.<br>
                Let life be a deep let-go.<br>
                God opens millions of flowers every day<br>
                without forcing their buds.”  —Osho
            </p>
        </div>
        @if (TempData["Message"] != null)
        {
            @if (TempData["Message"] != null)
            {
                <div class="alert alert-@TempData["MsgType"]">
                    @TempData["Message"]
                </div>
            }

        }
    </div>
</body>

C300/Views/Main/trends.cshtml
@model Product;
<style>
    .body {
        background-image: linear-gradient(150deg,#FFFFFF,#DDF3FB);
        height: 100vh;
        width: 100%;
    }
    h1 {
        font-family: Segoe Print;
        text-align: center;
    }

    .form-group {
        font-family: MV Boli;
        text-align: right;
    }
</style>
<body class="body">
   
    <div class="container">
        <form asp-controller ="Main"
              asp-action="trendsPost"
              method="post">
            <h1>Trends</h1>

            <div class="form-group row">
                <label class="control-label col-md-3" for="Display">Product Display:</label>
                <div class="col-md-6">
                    <select class="form-control checkbox" asp-for="Id">
                        @foreach (Product row in ViewData["Category"] as List<Product>)
                        {
                            <option value="@row.Id">
                                @row.Description
                            </option>
                        }
                    </select>
                </div>
                <label class="control-label col-md-3" for="chart">Chart:</label>
                <div class="col-md-6">
                    <select class="form-control dropdown" name="Trends" id="trends">
                        <option class="col-md-3" value="">-- SELECT --</option>
                        <option class="col-md-3" value="pie">Pie</option>
                        <option class="col-md-3" value="bar">Bar</option>
                        <option class="col-md-3" value="line">Line</option>
                    </select>
                </div>
                <div class="form-group row" style="text-align:left;font-family: Kristen ITC">
                    <div class="offset-md-3 col-md-6">
                        <input type="submit" class="btn btn-primary" value="Select" />
                    </div>
                </div>
            </div>
        </form>
    </div>
</body>